apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: kendrick-datadog-lab
    site: us5.datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    kubelet:
      tlsVerify: false
    tags:
      - env:lab
      - owner:kendrick-ng

  features:
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
      unixDomainSocketConfig:
        enabled: false

    logCollection:
      enabled: true
      containerCollectAll: true

    liveContainerCollection:
      enabled: true

    kubeStateMetricsCore:
      enabled: true

    eventCollection:
      collectKubernetesEvents: true